# Generated by Django 2.1 on 2020-02-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lecturename', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('userpw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserLecture',
            fields=[
                ('myuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='myuserid', serialize=False, to='swuapp.User')),
                ('rating', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=10)),
                ('mylectureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylectureid', to='swuapp.Lecture')),
                ('mysemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysemester', to='swuapp.Lecture')),
            ],
        ),
    ]
