# Generated by Django 2.1 on 2020-02-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlecture',
            name='myuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='myuserid', serialize=False, to='swuapp.User', unique=True),
        ),
    ]
