# Generated by Django 2.1 on 2020-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0004_auto_20200222_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='semester',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='lecture',
            name='gradepoint',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturediv',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
