# Generated by Django 2.1 on 2020-02-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0005_auto_20200223_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='gradepoint',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecturediv',
        ),
    ]
